### ISSUE TITLE
Kernel parameters errors

### ISSUE THREAD

**Issue by jasonmead** [jjasghar/rabbitmq#124]
==> default: Recipe Compile Error in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rabbitmq/recipes/default.rb
==> default: ================================================================================
==> default:
==> default:
==> default: NoMethodError
==> default: -------------
==> default: undefined method `each_pair' for []:Array
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rabbitmq/libraries/default.rb:38:in `format_kernel_parameters'
==> default:   /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rabbitmq/recipes/default.rb:163:in `from_file'
==> default:   /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rabbitmq/recipes/default.rb:157:in `from_file'
==> default:
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks/rabbitmq/libraries/default.rb:
==> default:
==> default:  31:        kernel.delete(:inet_dist_use_interface)
==> default:  32:
==> default:  33:        # Otherwise, we can just render it nicely as Erlang wants. This
==> default:  34:        # theoretically opens the door for arbitrary kernel_app parameters to be
==> default:  35:        # declared.
==> default:  36:
==> default:  37:         puts kernel.select { |k, v| !v.nil? }
==> default:  38>>       kernel.select { |k, v| !v.nil? }.each_pair do |param, val|
==> default:  39:          rendered << "{#{param}, #{val}}"
==> default:  40:        end
==> default:  41:
==> default:  42:        rendered.each { |r| r.prepend('    ') }.join(",\n")
==> default:  43:      end
==> default:  44:    end
==> default:  45:  end
==> default:  46:
==> default:

Trying to get Rabbit installed in vagrant CentOs using chef.  Using default recipe.  Any help would be appreciated.

**Comment by kirkbackus** [comment]
If you want to fix it yourself, you can change lines 38 - 40 to this

    kernel.select { |_k, v| !v.nil? }.each { |param, val|
        rendered << "{#{param}, #{val}}"
    }

kernel is an associative array (aka. hash in ruby), and they are iterating over it incorrectly.

**Comment by cmluciano** [comment]
@jasonmead Did you get this resolved?

**Comment by cmluciano** [comment]
Closing due to inactivity
